/** timeout-bounded, size-capped, redirect-revalidating fetch. */
import {assertSafeUrl,UnsafeUrlError} from './url-guard.js';
import type {SafeFetchOptions,SafeFetchResult} from '../types.js';
function env(name:string,fallback:string):string { const p=(globalThis as typeof globalThis & {process?:{env?:Record<string,string|undefined>}}).process; return p?.env?.[name]??fallback; }
const DEFAULTS={timeoutMs:Number(env('FETCH_TIMEOUT_MS','8000')),maxBytes:Number(env('FETCH_MAX_BYTES','2000000')),maxRedirects:Number(env('FETCH_MAX_REDIRECTS','3')),userAgent:env('FETCH_USER_AGENT','url-metadata-social-fetcher/1.0.0.1 (+https://github.com/vpicciuolo/url-metadata-social-fetcher)')};
const REDIRECT_CODES=new Set([301,302,303,307,308]);
async function readCapped(response:Response,maxBytes:number):Promise<{bytes:Uint8Array;truncated:boolean}>{const reader=response.body?.getReader();if(!reader){const buffer=new Uint8Array(await response.arrayBuffer().catch(()=>new ArrayBuffer(0)));return{bytes:buffer.slice(0,maxBytes),truncated:buffer.length>maxBytes};}const chunks:Uint8Array[]=[];let total=0,truncated=false;for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;if(total+value.length>maxBytes){chunks.push(value.slice(0,maxBytes-total));total=maxBytes;truncated=true;await reader.cancel().catch(()=>undefined);break;}chunks.push(value);total+=value.length;}const bytes=new Uint8Array(total);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}return{bytes,truncated};}
export async function safeFetch(input:string,options:SafeFetchOptions={}):Promise<SafeFetchResult>{const timeoutMs=options.timeoutMs??DEFAULTS.timeoutMs,maxBytes=options.maxBytes??DEFAULTS.maxBytes,maxRedirects=options.maxRedirects??DEFAULTS.maxRedirects;let current=assertSafeUrl(input,options).toString(),hops=0;for(;;){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(current,{method:options.method??'GET',redirect:'manual',signal:controller.signal,headers:{'user-agent':options.userAgent??DEFAULTS.userAgent,accept:'*/*','accept-language':'en',...options.headers}});if(REDIRECT_CODES.has(response.status)){const location=response.headers.get('location');await response.body?.cancel().catch(()=>undefined);if(!location)return{ok:false,status:response.status,url:current,contentType:'',bytes:new Uint8Array(0),text:'',truncated:false};if(++hops>maxRedirects)throw new UnsafeUrlError(`Too many redirects for ${input}`);current=assertSafeUrl(new URL(location,current).toString(),options).toString();continue;}const contentType=(response.headers.get('content-type')??'').toLowerCase();if(options.allowContentTypes?.length&&!options.allowContentTypes.some(prefix=>contentType.startsWith(prefix.toLowerCase()))){await response.body?.cancel().catch(()=>undefined);return{ok:false,status:response.status,url:current,contentType,bytes:new Uint8Array(0),text:'',truncated:false};}const declared=Number(response.headers.get('content-length')??'0');if(declared&&declared>maxBytes){await response.body?.cancel().catch(()=>undefined);return{ok:false,status:response.status,url:current,contentType,bytes:new Uint8Array(0),text:'',truncated:true};}const{bytes,truncated}=await readCapped(response,maxBytes);const isText=/^(text\/|application\/(json|xml|xhtml|ld\+json))/.test(contentType);return{ok:response.ok,status:response.status,url:current,contentType,bytes,text:isText?new TextDecoder('utf-8').decode(bytes):'',truncated};}finally{clearTimeout(timer);}}}
export function fetchDocument(url:string,options:SafeFetchOptions={}){return safeFetch(url,{...options,allowContentTypes:options.allowContentTypes??['text/html','application/xhtml+xml','text/plain'],headers:{accept:'text/html,application/xhtml+xml;q=0.9,*/*;q=0.5',...options.headers}});}
export function fetchImage(url:string,options:SafeFetchOptions={}){return safeFetch(url,{...options,allowContentTypes:['image/'],maxBytes:options.maxBytes??5_000_000,headers:{accept:'image/*',...options.headers}});}
