/** URL validation guard — blocks SSRF vectors before any network call. */
const PRIVATE_V4=[/^0\./,/^10\./,/^127\./,/^169\.254\./,/^172\.(1[6-9]|2\d|3[01])\./,/^192\.168\./,/^192\.0\.0\./,/^198\.(1[89])\./,/^100\.(6[4-9]|[7-9]\d|1[01]\d|12[0-7])\./,/^22[4-9]\./,/^23\d\./,/^24\d\./,/^25[0-5]\./];
const BLOCKED_HOST_SUFFIXES=['.local','.internal','.localdomain','.home.arpa'];
const BLOCKED_HOSTS=new Set(['localhost','metadata.google.internal','instance-data']);
export class UnsafeUrlError extends Error { constructor(message:string){super(message);this.name='UnsafeUrlError';} }
function isPrivateIpv4(host:string){return /^\d{1,3}(\.\d{1,3}){3}$/.test(host)&&PRIVATE_V4.some(re=>re.test(host));}
function isPrivateIpv6(host:string){const h=host.replace(/^\[|\]$/g,'').toLowerCase();return h.includes(':')&&(h==='::'||h==='::1'||h.startsWith('fc')||h.startsWith('fd')||h.startsWith('fe80')||h.startsWith('::ffff:'));}
function hostMatches(host:string,pattern:string){const p=pattern.toLowerCase().replace(/^\./,'');return host===p||host.endsWith(`.${p}`);}
export interface GuardOptions { allowHosts?:string[]; denyHosts?:string[]; }
export function assertSafeUrl(input:string,options:GuardOptions={}):URL { let url:URL; try{url=new URL(input);}catch{throw new UnsafeUrlError(`Not a valid absolute URL: ${input}`);} if(url.protocol!=='http:'&&url.protocol!=='https:')throw new UnsafeUrlError(`Blocked protocol: ${url.protocol}`); if(url.username||url.password)throw new UnsafeUrlError('Credentials in URL are not allowed'); const host=url.hostname.toLowerCase(); if(!host||BLOCKED_HOSTS.has(host))throw new UnsafeUrlError(`Blocked host: ${host}`); if(BLOCKED_HOST_SUFFIXES.some(s=>host.endsWith(s)))throw new UnsafeUrlError(`Blocked host suffix: ${host}`); if(isPrivateIpv4(host)||isPrivateIpv6(host))throw new UnsafeUrlError(`Blocked private address: ${host}`); if(!host.includes('.')&&!options.allowHosts?.some(p=>hostMatches(host,p)))throw new UnsafeUrlError(`Blocked non-public hostname: ${host}`); const port=url.port?Number(url.port):url.protocol==='https:'?443:80; if(![80,443,8080,8443].includes(port))throw new UnsafeUrlError(`Blocked port: ${port}`); if(options.allowHosts?.length&&!options.allowHosts.some(p=>hostMatches(host,p)))throw new UnsafeUrlError(`Host not in allowlist: ${host}`); if(options.denyHosts?.some(p=>hostMatches(host,p)))throw new UnsafeUrlError(`Host in denylist: ${host}`); return url; }
export function isSafeUrl(input:string,options:GuardOptions={}):boolean { try{assertSafeUrl(input,options);return true;}catch{return false;} }
export function normalizeUrl(input:string):string { const url=new URL(input);url.hash='';url.hostname=url.hostname.toLowerCase().replace(/^www\./,'');const drop=[/^utm_/,/^fbclid$/, /^gclid$/, /^igshid$/, /^mc_/, /^ref$/, /^si$/];for(const key of [...url.searchParams.keys()])if(drop.some(re=>re.test(key)))url.searchParams.delete(key);if(url.pathname.length>1)url.pathname=url.pathname.replace(/\/+$/,'');return url.toString().replace(/\/$/,''); }
