/** Zero-dependency HTML metadata extraction: title, meta, links, JSON-LD and social links. */
import type {PageMetadata} from '../types.js';
const ENTITIES:Record<string,string>={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'",'#39':"'",nbsp:' '};
const SOCIAL_HOSTS=['instagram.com','threads.net','threads.com','facebook.com','tiktok.com','youtube.com','youtu.be','x.com','twitter.com','linkedin.com','github.com','t.me','telegram.me','soundcloud.com','twitch.tv','spotify.com','pinterest.com','snapchat.com','discord.gg','discord.com'];
export function decodeEntities(input:string):string{return input.replace(/&(#x?[0-9a-fA-F]+|[a-zA-Z]+);/g,(match,code:string)=>{if(code.startsWith('#x')||code.startsWith('#X'))return String.fromCodePoint(parseInt(code.slice(2),16));if(code.startsWith('#')){const num=Number(code.slice(1));return Number.isFinite(num)?String.fromCodePoint(num):match;}return ENTITIES[code.toLowerCase()]??match;}).trim();}
function attrs(tag:string):Record<string,string>{const out:Record<string,string>={};const re=/([a-zA-Z_:][-a-zA-Z0-9_:.]*)\s*=\s*("([^"]*)"|'([^']*)'|([^\s"'>]+))/g;let m:RegExpExecArray|null;while((m=re.exec(tag))){const key=(m[1]??'').toLowerCase();out[key]=decodeEntities(m[3]??m[4]??m[5]??'');}return out;}
function absolute(value:string|undefined,base:string):string|undefined{if(!value)return undefined;try{return new URL(value,base).toString();}catch{return undefined;}}
function firstNonEmpty(...values:Array<string|undefined>):string|undefined{for(const value of values)if(value&&value.trim())return value.trim();return undefined;}
function pick<K extends string>(key:K,value:string|undefined){return(value?{[key]:value}:{}) as Record<K,string>;}
function isSocialHost(hostname:string):boolean{const host=hostname.toLowerCase().replace(/^www\./,'');return SOCIAL_HOSTS.some(candidate=>host===candidate||host.endsWith(`.${candidate}`));}
export function extractSocialLinks(html:string,baseUrl:string,limit=30):string[]{const found=new Set<string>();for(const tag of html.match(/<a\b[^>]*>/gi)??[]){const href=attrs(tag)['href'];if(!href)continue;try{const url=new URL(href,baseUrl);if(!/^https?:$/.test(url.protocol)||!isSocialHost(url.hostname))continue;url.hash='';found.add(url.toString());if(found.size>=limit)break;}catch{}}return[...found];}
export function extractMetadata(html:string,baseUrl:string):PageMetadata{const raw:Record<string,string>={};const links:Array<{rel:string;href:string;sizes?:string;type?:string}>=[];for(const tag of html.match(/<meta\b[^>]*>/gi)??[]){const a=attrs(tag);const key=(a['property']??a['name']??a['itemprop']??'').toLowerCase();const value=a['content']??a['value'];if(key&&value&&raw[key]===undefined)raw[key]=value;}for(const tag of html.match(/<link\b[^>]*>/gi)??[]){const a=attrs(tag);if(a['rel']&&a['href'])links.push({rel:a['rel'].toLowerCase(),href:a['href'],...(a['sizes']?{sizes:a['sizes']}:{ }),...(a['type']?{type:a['type']}:{ })});}const titleTag=/<title[^>]*>([\s\S]*?)<\/title>/i.exec(html)?.[1];const jsonLd=extractJsonLd(html);const canonical=links.find(l=>l.rel.split(/\s+/).includes('canonical'))?.href;const icon=links.find(l=>l.rel.includes('apple-touch-icon'))?.href??links.find(l=>l.rel.split(/\s+/).some(r=>r==='icon'||r==='shortcut'))?.href??'/favicon.ico';const keywords=(raw['keywords']??raw['article:tag']??'').split(',').map(k=>k.trim()).filter(Boolean).slice(0,25);const brandColors=[...new Set([raw['theme-color'],raw['msapplication-tilecolor'],raw['msapplication-navbutton-color']].filter((value):value is string=>Boolean(value&&value.trim())))].slice(0,5);return{url:baseUrl,...pick('canonicalUrl',absolute(canonical,baseUrl)),...pick('title',firstNonEmpty(raw['og:title'],raw['twitter:title'],jsonLd?.['name'] as string|undefined,titleTag?decodeEntities(titleTag):undefined)),...pick('description',firstNonEmpty(raw['og:description'],raw['twitter:description'],raw['description'],jsonLd?.['description'] as string|undefined)),...pick('siteName',firstNonEmpty(raw['og:site_name'],raw['application-name'])),...pick('imageUrl',absolute(firstNonEmpty(raw['og:image:secure_url'],raw['og:image'],raw['twitter:image'],raw['twitter:image:src'],typeof jsonLd?.['image']==='string'?jsonLd['image'] as string:undefined),baseUrl)),...pick('iconUrl',absolute(icon,baseUrl)),...pick('themeColor',raw['theme-color']),brandColors,...pick('locale',firstNonEmpty(raw['og:locale'],raw['language'])),...pick('author',firstNonEmpty(raw['author'],raw['article:author'],raw['twitter:creator'])),...pick('publishedAt',firstNonEmpty(raw['article:published_time'],raw['date'])),...pick('type',firstNonEmpty(raw['og:type'],jsonLd?.['@type'] as string|undefined)),keywords,socialLinks:extractSocialLinks(html,baseUrl),raw};}
export function extractJsonLd(html:string):Record<string,unknown>|undefined{const blocks=html.match(/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)??[];for(const block of blocks){const body=block.replace(/^[\s\S]*?>/,'').replace(/<\/script>$/i,'');try{const parsed=JSON.parse(body) as unknown;const graph=(parsed as {'@graph'?:unknown[]})?.['@graph'];const candidates=Array.isArray(parsed)?parsed:graph??[parsed];for(const candidate of candidates as Record<string,unknown>[])if(candidate&&typeof candidate==='object')return candidate;}catch{}}return undefined;}
export function extractText(html:string,maxChars=4000):string{const stripped=html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<noscript[\s\S]*?<\/noscript>/gi,' ').replace(/<[^>]+>/g,' ');return decodeEntities(stripped).replace(/\s+/g,' ').trim().slice(0,maxChars);}
